version: '3'

services:
  collo-grpc:
    build:
      context: ../
      dockerfile: ./.docker/dockerfile.local
    container_name: "collo-grpc"
    volumes:
      - ../:/workspaces/collo-grpc:cached
    tty: true