FROM mcr.microsoft.com/devcontainers/go:1-1.21-bullseye

RUN sudo apt-get update && \
  sudo apt-get install -y protobuf-compiler && \
  go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
  go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest